### ISSUE TITLE
Ban IPs requesting too often

### ISSUE THREAD

**Issue by jackbisceglia** [jackbisceglia/apptrack#121]
Rate Limiter will help short term. Need a way to ban IPs that are consistently spamming.

Ideas:
- Upon X number of 429 responses (essentially response saying "you're spamming"), we add to a Redis Banlist, and block any IP in Redist banlist upon future requests
  - Redis is in memory, so this isn't quite persistent, though it will "persist" long enough to satisfy our use case

**Comment by HeroCC** [comment]
Maybe throw the whole thing in front of Cloudflare? It handles the limiting and cache pretty well in my experience.

**Comment by jackbisceglia** [comment]
Yea I should definitely look into this. Thanks for the suggestion
