### ISSUE TITLE
UI Page to display job listings

### ISSUE THREAD

**Issue by jackbisceglia** [jackbisceglia/apptrack#26]
Should pretty much be a nicer version of the GitHub README's.

The 2 that we are using for Intern and New Grad respectively are:
- https://github.com/pittcsc/Summer2023-Internships
- https://github.com/coderQuad/New-Grad-Positions-2023

API Endpoint to get all job postings is a GET to: `localhost:8080/postings/`
- Returns the job postings in the following shape:
```
{
    "NewGradPosts": [{...}, {...}],
    "InternPosts": [{...}, {...}],
}
```

**Just one page with 2 tabs to display the jobs in table form. 1 tab for intern posts, and the other for newgrad**
Route preferably: https://domain/joblistings, or something like that

**Comment by joepetrillo** [comment]
Starting working on this today, might need some help with figuring out how we want the UI to look its a little tricky.

**Comment by jackbisceglia** [comment]
> 
Got any screenshots?

**Comment by joepetrillo** [comment]
Going to include a bunch so you know the current "feel" of the app.

![image](https://user-images.githubusercontent.com/32227357/177906307-eae69de1-f139-48a5-9fff-39e07d0be8b2.png)

![image](https://user-images.githubusercontent.com/32227357/177906275-803232aa-681b-4bd5-b0fa-e8a2c98e7174.png)

![image](https://user-images.githubusercontent.com/32227357/177906338-ae7cdbff-e74b-4636-9d34-5c2b0387ee7d.png)

https://user-images.githubusercontent.com/32227357/177906621-2da18135-9863-4e42-86d5-7ca6a2bd6c62.mov

Still need to work on the tags and a lot more but I think it is shaping up nicely so far.

**Comment by jackbisceglia** [comment]
Looks really good

Thoughts: 
- onHover we can replace box contents with Notes and Location information (if present) (maybe like overlay the original content with it, low opacity background or something
- Company title shouldn't be tooooo long in theory
- Filters:
  - Intern/NewGrad
  - Date Added
  - Can do some parsing of the location to *try* and accurately get the State. Split by ',' or something
