### ISSUE TITLE
Seperate intern postings and new grad postings in emails

### ISSUE THREAD

**Issue by joepetrillo** [jackbisceglia/apptrack#92]
It is possible that a user selects to be updated for both internships and new grad roles (intended behavior).

However, it is not clear what each post listed in our emails pertains to. We should just separate them in the email with some sort of heading or indicator next to the location.

Not urgent.

**Comment by nabilbaugher** [comment]
For people who have signed up for both, the email will now say '[Intern]' or '[New Grad]' in front of the normal subject
